/*    */ package nencer.app.Modules.Medic.Model.Response.MedicTreatment;
/*    */ public class TreatmentDetailModel { private Integer treatmentId;
/*    */   private Integer serviceGroupId;
/*    */   private String serviceGroupName;
/*    */   private Integer ticketId;
/*    */   private String title;
/*    */   
/*  8 */   public void setTreatmentId(Integer treatmentId) { this.treatmentId = treatmentId; } public void setServiceGroupId(Integer serviceGroupId) { this.serviceGroupId = serviceGroupId; } public void setServiceGroupName(String serviceGroupName) { this.serviceGroupName = serviceGroupName; } public void setTicketId(Integer ticketId) { this.ticketId = ticketId; } public void setTitle(String title) { this.title = title; } public boolean equals(Object o) { if (o == this) return true;  if (!(o instanceof TreatmentDetailModel)) return false;  TreatmentDetailModel other = (TreatmentDetailModel)o; if (!other.canEqual(this)) return false;  Object this$treatmentId = getTreatmentId(), other$treatmentId = other.getTreatmentId(); if ((this$treatmentId == null) ? (other$treatmentId != null) : !this$treatmentId.equals(other$treatmentId)) return false;  Object this$serviceGroupId = getServiceGroupId(), other$serviceGroupId = other.getServiceGroupId(); if ((this$serviceGroupId == null) ? (other$serviceGroupId != null) : !this$serviceGroupId.equals(other$serviceGroupId)) return false;  Object this$serviceGroupName = getServiceGroupName(), other$serviceGroupName = other.getServiceGroupName(); if ((this$serviceGroupName == null) ? (other$serviceGroupName != null) : !this$serviceGroupName.equals(other$serviceGroupName)) return false;  Object this$ticketId = getTicketId(), other$ticketId = other.getTicketId(); if ((this$ticketId == null) ? (other$ticketId != null) : !this$ticketId.equals(other$ticketId)) return false;  Object this$title = getTitle(), other$title = other.getTitle(); return !((this$title == null) ? (other$title != null) : !this$title.equals(other$title)); } protected boolean canEqual(Object other) { return other instanceof TreatmentDetailModel; } public int hashCode() { int PRIME = 59; result = 1; Object $treatmentId = getTreatmentId(); result = result * 59 + (($treatmentId == null) ? 43 : $treatmentId.hashCode()); Object $serviceGroupId = getServiceGroupId(); result = result * 59 + (($serviceGroupId == null) ? 43 : $serviceGroupId.hashCode()); Object $serviceGroupName = getServiceGroupName(); result = result * 59 + (($serviceGroupName == null) ? 43 : $serviceGroupName.hashCode()); Object $ticketId = getTicketId(); result = result * 59 + (($ticketId == null) ? 43 : $ticketId.hashCode()); Object $title = getTitle(); return result * 59 + (($title == null) ? 43 : $title.hashCode()); } public String toString() { return "TreatmentDetailModel(treatmentId=" + getTreatmentId() + ", serviceGroupId=" + getServiceGroupId() + ", serviceGroupName=" + getServiceGroupName() + ", ticketId=" + getTicketId() + ", title=" + getTitle() + ")"; }
/*  9 */   public static TreatmentDetailModelBuilder builder() { return new TreatmentDetailModelBuilder(); } public static class TreatmentDetailModelBuilder { private Integer treatmentId; private Integer serviceGroupId; public TreatmentDetailModelBuilder treatmentId(Integer treatmentId) { this.treatmentId = treatmentId; return this; } private String serviceGroupName; private Integer ticketId; private String title; public TreatmentDetailModelBuilder serviceGroupId(Integer serviceGroupId) { this.serviceGroupId = serviceGroupId; return this; } public TreatmentDetailModelBuilder serviceGroupName(String serviceGroupName) { this.serviceGroupName = serviceGroupName; return this; } public TreatmentDetailModelBuilder ticketId(Integer ticketId) { this.ticketId = ticketId; return this; } public TreatmentDetailModelBuilder title(String title) { this.title = title; return this; } public TreatmentDetailModel build() { return new TreatmentDetailModel(this.treatmentId, this.serviceGroupId, this.serviceGroupName, this.ticketId, this.title); } public String toString() { return "TreatmentDetailModel.TreatmentDetailModelBuilder(treatmentId=" + this.treatmentId + ", serviceGroupId=" + this.serviceGroupId + ", serviceGroupName=" + this.serviceGroupName + ", ticketId=" + this.ticketId + ", title=" + this.title + ")"; }
/*    */      } public TreatmentDetailModel() {} public TreatmentDetailModel(Integer treatmentId, Integer serviceGroupId, String serviceGroupName, Integer ticketId, String title) {
/* 11 */     this.treatmentId = treatmentId; this.serviceGroupId = serviceGroupId; this.serviceGroupName = serviceGroupName; this.ticketId = ticketId; this.title = title;
/*    */   }
/* 13 */   public Integer getTreatmentId() { return this.treatmentId; }
/* 14 */   public Integer getServiceGroupId() { return this.serviceGroupId; }
/* 15 */   public String getServiceGroupName() { return this.serviceGroupName; }
/* 16 */   public Integer getTicketId() { return this.ticketId; } public String getTitle() {
/* 17 */     return this.title;
/*    */   } }


/* Location:              C:\Users\Administrator\Desktop\!\nencer\app\Modules\Medic\Model\Response\MedicTreatment\TreatmentDetailModel.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */